### ISSUE TITLE
Memory leak on v2.2.1 and above

### ISSUE THREAD

**Issue by FamilyMan** [evo-mark/vue3-snackbar#12]
v2.2.0 works fine, if I upgrade to v2.2.1 it introduces a memory leak. I have a project deployed to K8S, if I use v2.2.1 or above the memory increases and the pod restarts, this occurs very quickly, within 3 minutes.

**Comment by craigrileyuk** [comment]
@FamilyMan There was only one thing that changed for that release that could've been connected to this issue, so I've pushed a v2.3.1 which reverts it.

Let me know if that fixes the problem for you.

**Comment by FamilyMan** [comment]
@craigrileyuk I tried v2.3.1 & v2.3.2 but unfortunately the problem persists. I'm back to v2.2.0

**Comment by FamilyMan** [comment]
I am now using version 2.3.2 and the memory leak has gone. I am using this on Nuxt with nuxt-snackbar (which is now at version 1.1.2), so there must have been some fix they have added to their latest version.

**Comment by craigrileyuk** [comment]
If you can post any more information about how I can reproduce the error, I'll investigate it more thoroughly for you.

Does the leak issue occur with a standard Nuxt install, or is it only via a K8s deployment?

**Comment by craigrileyuk** [comment]
Closing this since no further info was supplied and it seems to be an edge case.
